services:
  self-ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: self-ollama
    tty: true
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama

  self-llamolotl:
    image: local/self-llamolotl:latest
    build:
      context: ./self.llamolotl
      dockerfile: Dockerfile
      pull: false
    container_name: self-llamolotl
    volumes:
      - /srv/llamolotl/models:/models
      - /srv/llamolotl/loras:/workspace/training/outputs
      - /srv/llamolotl/cache:/workspace/cache
    env_file:
      - ./self.llamolotl/self.Llama/.env
    environment:
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-}
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - DEBUG=1
    ports:
      - 8091:8080
      - 8093:8093
    networks:
      - llama_internal
      - proxy_llama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  self-kokoro:
    image: local/self-kokoro:latest
    build:
      context: ./self.kokoro-fastapi
      dockerfile: docker/gpu/Dockerfile
      pull: false
    container_name: self-kokoro
    volumes:
      - /srv/kokoro/models:/app/api/src/models
      - /srv/kokoro/voices:/app/api/src/voices
    environment:
      - DOWNLOAD_MODEL=true
      - DEFAULT_VOICE=af_jessica
      - USE_GPU=true
      - CORS_ORIGINS=["*"]
    ports:
      - 8880:8880
    networks:
      - proxy_llama
      - llama_internal
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  self-faster-whisper:
    image: local/self-faster-whisper:latest
    build:
      context: ./self.faster-whisper
      dockerfile: Dockerfile
    container_name: self-faster-whisper
    volumes:
      - /srv/faster-whisper/models:/models
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - WHISPER_COMPUTE_TYPE=${WHISPER_COMPUTE_TYPE:-float16}
    ports:
      - "8890:8890"
    networks:
      - llama_internal
      - proxy_llama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  selfUI:
    image: local/self.ai-ui:latest
    pull_policy: build
    build:
      context: ./self.UI
      dockerfile: Dockerfile
      pull: true
      #no_cache: true
    container_name: selfUI
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TIMEZONE=America/Los_Angeles
      - LM_EVAL_RESULTS_DIR=/app/backend/data/lm-eval-results
    volumes:
      - selfUI-data:/app/backend/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./self.bigcode-eval/results:/app/backend/data/bigcode-results:ro
      - ./self.lm-evaluation-harness/results:/app/backend/data/lm-eval-results:ro
      - ./self.lm-evaluation-harness/logs:/app/backend/data/lm-eval-logs:ro
    depends_on:
      #Databases
      - self-postgres
      - self-valkey
      - self-qdrant
      #Inference
      - self-llamolotl
      - self-ollama
      #Speech-to-Text-to-Speech
      - self-faster-whisper
      - self-kokoro
      #HTTPS Proxy
      - self-traefik
    ports:
      - ${SELFAI_UI_PORT-3000}:8080
    env_file:
      - ./self.UI/.env
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - proxy_llama
      - llama_internal
  
  # self-swagger-ui:
  #   image: swaggerapi/swagger-ui:latest
  #   container_name: swaggerUI
  #   profiles:
  #     - development
  #   environment:
  #     SWAGGER_JSON: /tmp/openapi.yaml
  #   volumes:
  #     - ./openapi.with-code-samples.yml:/tmp/openapi.yaml:ro
  #   ports:
  #     - 8092:8080
  #   restart: unless-stopped

  self-postgres:
    image: postgres:18
    restart: unless-stopped
    container_name: self-postgres
    env_file: 
      - ./postgres/.env
    volumes:
      - selfUI-db:/var/lib/postgresql
    networks:
      - llama_internal
  adminer:
    image: adminer:latest
    profiles:
      - troubleshoot
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8094:8080
    networks:
      - llama_internal
      - proxy_llama
  
  # redis database for paperless-ngx
  self-valkey:
    image: docker.io/valkey/valkey:8
    container_name: self-valkey
    restart: unless-stopped
    env_file: 
      - ./valkey/.env
    volumes:
      - self-valkey-data:/data
      - ./valkey/conf/valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    networks:
      - llama_internal

  self-traefik:
    image: traefik:v3.6
    container_name: self-traefik
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

#    environment:
      # Route53 needs a region set (Route53 is “global” but the AWS SDK still wants one)
      #- AWS_REGION=us-east-1
    env_file:
      - /opt/ai-stack/traefik/.env.traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=ai-internal

      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # - --certificatesresolvers.ipa.acme.email=you@mateysmarsh.com
      # - --certificatesresolvers.ipa.acme.storage=/letsencrypt/ipa-acme.json
      # - --certificatesresolvers.ipa.acme.caserver=https://ipa-ca.home.mateysmarsh.com/acme/directory
      # - --certificatesresolvers.ipa.acme.cacertificates=/etc/ssl/certs/ipa-ca.crt
      # - --certificatesresolvers.ipa.acme.httpchallenge.entrypoint=web

      # # Let's Encrypt (TLS-ALPN challenge over 443)
      #- --certificatesresolvers.le.acme.dnsChallenge=true
      #- --certificatesresolvers.le.acme.dnsChallenge.provider=route53
      #- --certificatesresolvers.le.acme.dnsChallenge=marshmatey@mateysmarsh.com
      #- --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json

      # Logging (optional)
      - --log.level=INFO
      - --accesslog=true
      
      #File Providers
      - --providers.file.directory=/dynamic

    ports:
      - "80:80"
      - "443:443"
      # Optional: expose dashboard on the host (lock this down if you do)
      #- "8080:8080"

    volumes:
      # - /etc/ipa/ca.crt:/etc/ssl/certs/ipa-ca.crt:ro

      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt:/letsEncrypt:ro
      - ./traefik/config:/dynamic:ro

    networks:
      - proxy_llama
      - llama_internal
    
  self-qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: self-qdrant
    # ports:
    #   - 6333:6333
    #   - 6334:6334
    # configs:
    #   - source: qdrant_config
    #     target: /qdrant/config/production.yaml
    volumes:
      - ./self.qdrant/data:/qdrant/storage
      - ./self.qdrant/configs:/qdrant/config
    networks:
      - llama_internal
  

  self-bigcode-eval:
    image: local/self-bigcode-eval:latest
    build:
      context: ./self.bigcode-eval
      dockerfile: Dockerfile
      pull: false
    container_name: self-bigcode-eval
    ports:
      - 8095:8094
    # profiles:
    #   - eval
    volumes:
      - hf-eval-cache:/root/.cache/huggingface/
      - ./self.bigcode-eval/results:/workspace/results
      - bigcode-logs:/workspace/logs
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
    networks:
      - llama_internal
      - proxy_llama
    restart: unless-stopped

  self-lm-eval:
    image: local/self-lm-eval:latest
    build:
      context: ./self.lm-evaluation-harness
      dockerfile: Dockerfile
      pull: false
    container_name: self-lm-eval
    ports:
      - 8097:8096
    volumes:
      - hf-eval-cache:/root/.cache/huggingface/
      - ./self.lm-evaluation-harness/results:/workspace/results
      - ./self.lm-evaluation-harness/logs:/workspace/logs
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
    networks:
      - llama_internal
      - proxy_llama
    restart: unless-stopped

  self-curator:
    image: local/self-curator:latest
    build:
      context: ./self.curator
      dockerfile: Dockerfile.selfai
      pull: false
    container_name: self-curator
    shm_size: '2gb'
    volumes:
      - selfUI-data:/workspace/ui-data
      - /srv/curator/data:/workspace/curator/data
      - /srv/curator/cache:/workspace/curator/cache
      - /srv/curator/configs:/workspace/curator/configs
      - /srv/curator/jobs:/workspace/curator/jobs
      - /srv/curator/logs:/workspace/curator/logs
      - /srv/curator/custom_stages:/workspace/curator/custom_stages
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - RAY_OBJECT_STORE_MEMORY=2000000000
    networks:
      - llama_internal
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # wyoming-whisper:
  #   image: rhasspy/wyoming-whisper
  #   container_name: wyoming-whisper
  #   #entrypoint: ["script/run"]
  #   command:
  #     - --model
  #     - tiny-int8
  #     - --language
  #     - en
  #     - --uri
  #     - tcp://0.0.0.0:10300
  #     - --data-dir
  #     - /data
  #     - --download-dir
  #     - /data
  #   ports:
  #     - "10300:10300"
  #   volumes:
  #     - ./wyoming-whisper/data:/data
  #   stdin_open: true
  #   tty: true
  #   gpus: all
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  comfyui:
    image: yanwk/comfyui-boot:cu128-megapak-pt29
    container_name: comfyui
    ports:
      - "8188:8188"
    environment:
      - CLI_ARGS="--disable-xformers"
    volumes:
      - /srv/comfyui/models:/root/ComfyUI/models 
      - /srv/comfyui/models/hf-hub:/root/.cache/huggingface/hub
      - /srv/comfyui/models/torch-hub:/root/.cache/torch/hub
      - /srv/comfyui/models/input:/root/ComfyUI/input
      - /srv/comfyui/models/output:/root/ComfyUI/output
      - /srv/comfyui/models/workflows:/root/ComfyUI/user/default/workflows
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - proxy_llama
      - llama_internal


networks:
  proxy_llama:
    name: proxy_llama
  llama_internal:
    name: llama_internal
    internal: true

volumes:
  ollama: {}
  open-webui: {}
  qdrant_config: {}
  selfUI-data: {}
  selfUI-db: {}
  self-valkey-data: {}
  hf-eval-cache: {}
  bigcode-logs: {}
