[http]
  [http.routers]
    [http.routers.scan]
      entryPoints = ["web", "websecure"]
      rule = "Host(`scan.home.mateysmarsh.com`)"
      service = "scan"
      [http.routers.scan.tls]
        [[tls.certificates]]
          certFile = "/letsEncrypt/live/scan.home.mateysmarsh.com/fullchain.pem"
          keyFile = "/letsEncrypt/live/scan.home.mateysmarsh.com/privkey.pem"
    [http.services]
      [http.services.scan.loadBalancer]
        strategy = "wrr"
      [[http.services.scan.loadBalancer.servers]]
        url = "http://paperless-gpt:8080/"